- name: "LÙN LỰC"
  image: "https://raw.githubusercontent.com/trinkse61538/AGVN/main/images/ThuocDieuHoaSinhTruong/LU%CC%80N%20LU%CC%9B%CC%A3C%20CATALOG.png"
  badge: "Thuốc Điều Hoà Sinh Trưởng"
  features:
    - "Điều hòa sinh trưởng, hạn chế chiều cao: Paclobutrazol ức chế quá trình sinh tổng hợp Gibberellin, giúp ngắn thân rạ, ngắn lóng, tăng độ dày thân cây."
    - "Mập thân – cứng cây – đứng lá: Giúp bộ lá dày, xanh bền, đứng thẳng, không gây phượt lá."
    - "Giảm đổ ngã, bảo vệ năng suất: Hạn chế đổ ngã khi gặp mưa gió, giúp giảm thất thoát năng suất và tiết kiệm chi phí thu hoạch."
    - "Giúp bộ rễ phát triển khỏe, đẻ nhánh gọn và hiệu quả nhờ điều tiết sinh trưởng cân đối, nâng cao hiệu quả sử dụng phân bón ngay từ giai đoạn đầu."
    - "Dạng huyền phù (SC) ưu việt: Thuốc dạng sữa dễ hòa tan hoàn toàn trong nước, giúp cây hấp thụ nhanh chóng và tối ưu qua lá, thân, rễ."

- name: "NUMBER ONE"
  image: "https://raw.githubusercontent.com/trinkse61538/AGVN/main/images/ThuocDieuHoaSinhTruong/NUMBER%20ONE%20(AGVN)%20catalog.png"
  badge: "Thuốc Điều Hoà Sinh Trưởng"
  features:
    - "Ưu điểm vượt trội của Pyraclostrobin kiểm soát hiệu quả many loại nấm là các tác nhân gây ra các loại bệnh phổ biến."
    - "Kích thích hoạt động quang hợp: Hoạt chất này làm tăng hàm lượng diệp lục tố, giúp lá cây xanh lâu hơn, nâng cao hiệu quả hấp thụ ánh sáng."
    - "Cải thiện khả năng hấp thụ dinh dưỡng và nước: Đặc biệt với Nitơ, cây trồng có thể sử dụng nguồn dinh dưỡng một cách tối ưu hơn, từ đó phát triển mạnh mẽ và đồng đều."
    - "Tăng cường sức đề kháng: với khả năng kích hoạt gen PR (Gen PR phòng thủ sinh học) cây trồng có khả năng chống chịu tốt hơn trước stress môi trường, bao gồm nhiệt độ cao, hạn hán hoặc độ ẩm cao."
    - "Kéo dài tuổi thọ lá: thuốc cũng có thể làm giảm tác dụng sinh học của ethylene tổng hợp, trì hoãn sự già đi của cây trồng, cải thiện hệ miễn dịch và khả năng chống lại các yếu tố tăng trưởng bất lợi, từ đó cải thiện năng suất và chất lượng nông sản."
