- name: "DIỆT CHÍCH HÚT"
  image: "https://raw.githubusercontent.com/trinkse61538/AGVN/main/images/ThuocTruSau/Die%CC%A3%CC%82t%20Chi%CC%81ch%20Hu%CC%81t%20catalouge.png"
  badge: "Thuốc Trừ Sâu - Rầy"
  features:
    - "Diệt nhanh, diệt sạch: Hiệu quả cực mạnh với nhiều loại côn trùng chích hút như: rầy nâu, rầy cánh trắng, bọ trĩ, rệp sáp, rầy xanh..."
    - "Không gây nóng bông, diệt sạch và ung trứng, cắt lứa nhanh chóng."
    - "Tính lưu dẫn cao, giúp thuốc di chuyển đến các bộ phận khác của cây."
    - "Hiệu lực kéo dài, hấp thu nhanh trong vòng 2-3 giờ, không bị rửa trôi khi gặp mưa."
    - "Pha trộn dễ dàng, hoà tan tốt, sử dụng tốt mọi giai đoạn cây trồng."

- name: "BÒ HÚC VÀNG"
  image: "https://raw.githubusercontent.com/trinkse61538/AGVN/main/images/ThuocTruSau/Bo%CC%80%20hu%CC%81c%20va%CC%80ng%20(aa%20faros)%20AGVN%20300ml%20catalog.png"
  badge: "Thuốc Trừ Sâu - Rầy"
  features:
    - "Đặc trị rầy nâu, rầy phấn trắng, bọ xít hôi, rệp sáp, bọ trĩ trên lúa."
    - "Kiểm soát hiệu quả rầy mềm, bọ trĩ, rệp sáp, bọ xít muỗi trên rau màu và cây ăn trái."
    - "Với dạng Huyền phù (SC) tiên tiến, thuốc thấm sâu, bám dính tốt và hấp thụ tối ưu mà không gây nóng cây, sử dụng an toàn trong mọi giai đoạn phát triển của cây trồng."

- name: "XÔNG HƠI B52"
  image: "https://raw.githubusercontent.com/trinkse61538/AGVN/main/images/ThuocTruSau/XO%CC%82NG%20HO%CC%9BI%20B52%20CATALOUGE.png"
  badge: "Thuốc Trừ Sâu - Rầy"
  features:
    - "Xông hơi cực mạnh: Lan tỏa khắp tán lá and thân cây, diệt cả côn trùng ẩn sâu bên trong."
    - "Tiếp xúc nhanh: Hiệu quả nhanh, kéo dài nhiều ngày giúp giảm số lần phun, tiết kiệm chi phí."
    - "Nội hấp: Nội hấp vượt trội, thấm sâu vào mô cây diệt tức thì côn trùng và ổ trứng gây hại."
